name = "customer table"
description = "create customers table"
up = """ 
  create table if not exists customer (
    id serial primary key,
    name varchar(255) not null,
    email varchar(255) not null,
    provider varchar(32) not null,
    provider_id varchar(255) not null,
    unique (provider, provider_id)
  );
"""

down = "drop table customer"
