description = "create customers table"
down = "DROP TABLE {{ .Schema }}.customer"
name = "customer table"
up = """ 
CREATE TABLE {{ .Schema }}.customer (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT Null,
	email VARCHAR(255) NOT Null,
	provider VARCHAR(32) NOT NUll,
	provider_id VARCHAR(255) NOT Null,
	UNIQUE (provider, provider_id)
);
"""
