name = "customer table"
description = "create customers table"
up = """ 
CREATE TABLE pay.customer (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT Null,
	email VARCHAR(255) NOT Null,
	provider VARCHAR(32) NOT NUll,
	provider_id VARCHAR(255) NOT Null,
	UNIQUE (provider, provider_id)
);
"""
down = "DROP TABLE pay.customer"
