description = "Creates a plan table"
down = "DROP TABLE pay.plan"
name = "plan_table"
up = """
CREATE TABLE {{ .Schema }}.plan(
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
    description TEXT,
	provider VARCHAR(255) NOT NULL,
	provider_id VARCHAR(255) NOT NULL,
	active BOOL NOT NULL
);
"""
