name = "plan_table"
description = "Creates a plan table"
up = """
CREATE TABLE pay.plan(
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	provider VARCHAR(255) NOT NULL,
	provider_id VARCHAR(255) NOT NULL,
	trial_days INT NOT NULL DEFAULT 0,
	active BOOL NOT NULL
);
"""
down = "DROP TABLE pay.plan"
