description = "Creates a subscription table"
down = "DROP TABLE {{ .Schema }}.subscription"
name = "subscription_table"
up = """
  CREATE TABLE IF NOT EXISTS {{ .Schema }}.subscription (
    id SERIAL PRIMARY KEY,
    customer_id INT NOT NULL,
    plan_id INT NOT NULL,
    provider VARCHAR(255) NOT NULL,
    provider_id VARCHAR(255) NOT NULL,
    active BOOL NOT NULL DEFAULT FALSE,
    FOREIGN KEY (customer_id) REFERENCES pay.customer(id),
    FOREIGN KEY (plan_id) REFERENCES pay.plan(id)
  );
"""
