description = "Creates a price table with a one to many relationship with plan"
down = "DROP TABLE {{ .Schema }}.price"
name = "price_table"
up = """
CREATE TABLE {{ .Schema }}.price (
	id SERIAL PRIMARY KEY,
	plan_id INT NOT NULL,
	provider VARCHAR(255) NOT NULL,
	provider_id VARCHAR(255) NOT NULL,
	currency VARCHAR(3) NOT NULL,
	amount INT NOT NULL DEFAULT 0,
	schedule VARCHAR(32) NOT NULL,
	FOREIGN KEY (plan_id) REFERENCES pay.plan (id),
	UNIQUE (provider, provider_id)
);
"""
