name = "add price id to subscription"
description = "Adds a price id column to subscription and foreign key relationship to subscription"
up = """
ALTER TABLE pay.subscription 
ADD COLUMN price_id INT NOT NULL;

ALTER TABLE pay.subscription 
ADD FOREIGN KEY(price_id) REFERENCES pay.price(id);
"""
down = """
ALTER TABLE pay.subscription 
DROP CONSTRAINT fk_subscription_price_id COLUMN price_id;

ALTER TABLE pay.subscription
DROP COLUMN price_id;
"""
